install.packages('rmarkdown', repos='cran.rstudio.com')
install.packages('Rcpp', repos='cran.rstudio.com')
install.packages('rprojroot', repos='cran.rstudio.com')
install.packages('tidyverse', repos='cran.rstudio.com')
install.packages('magrittr', repos='cran.rstudio.com')
install.packages('knitr', repos='cran.rstudio.com')
install.packages('kableExtra', repos='cran.rstudio.com')
install.packages('reticulate', repos='cran.rstudio.com')